name: gestor_gastos
description: Un nuevo proyecto Flutter para gestionar gastos.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  # Dependencias Ãºtiles para Clean Architecture
  dartz: ^0.10.1
  get_it: ^7.6.0
  provider: ^6.0.5
  equatable: ^2.0.5
  shared_preferences: ^2.5.4
  fl_chart: ^0.66.0
  intl: ^0.20.2
  table_calendar: ^3.2.0
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.2
  font_awesome_flutter: ^10.12.0
  confetti: ^0.8.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  flutter_markdown_plus: ^1.0.7
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
